<?php

add_action( 'acf/init', 'aic_fields' );
function aic_fields(){
	$theme_op_group_key = 'group_61a631ba28adb';
	$support_op_group_key = 'group_67d8386cb03f5';
	$location = 'aic-theme-options';
	$site_url = '?Website='.site_url().'';
	$user = wp_get_current_user();
	$name = '&Name='.$user->user_firstname.' '.$user->user_lastname.'';
	$email = '&Email='.$user->user_email.'';
	
	acf_add_local_field_group(array(
		'key' => $support_op_group_key,
		'title' => 'Send A Ticket',
		'fields' => array(
			array(
				'key' => 'field_67d8386c77793',
				'label' => '',
				'name' => 'support-form',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '<iframe class="clickup-embed clickup-dynamic-height" src="https://forms.clickup.com/1274607/f/16wqf-40/B5U3MXUHVQ8Q9HZRNU'.$site_url.$name.$email.'" onwheel="" width="100%" height="1325" style="background: transparent; border: 1px solid #ccc;"></iframe><script async src="https://app-cdn.clickup.com/assets/js/forms-embed/v1.js"></script>',
				'new_lines' => '',
				'esc_html' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'send-a-ticket'
				)
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'field',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

	acf_add_local_field_group(array(
		'key' => $theme_op_group_key,
		'title' => 'Theme Options',
		'fields' => array(
			array(
				'key' => 'field_61a631c11d93f',
				'label' => 'Theme Colors',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_61a632031d940',
				'label' => '',
				'name' => 'theme_colors',
				'type' => 'repeater',
				'instructions' => '<em class="dev-only">Field Name: theme_colors<br />Field Key: field_61a632031d940</em>',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => 'field_61a6323b1d941',
				'min' => 0,
				'max' => 0,
				'layout' => 'block',
				'button_label' => 'Add Color',
				'sub_fields' => array(
					array(
						'key' => 'field_61a6323b1d941',
						'label' => 'Color Name',
						'name' => 'color_name',
						'type' => 'text',
						'instructions' => '<em class="dev-only">Field Name: color_name<br />Field Key: field_61a6323b1d941</em>',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_61a632501d942',
						'label' => 'Color Hex',
						'name' => 'color_hex',
						'type' => 'color_picker',
						'instructions' => '<em class="dev-only">Field Name: color_hex<br />Field Key: field_61a632501d942</em>',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'enable_opacity' => 0,
						'return_format' => 'string',
					),
					array(
						'key' => 'field_6213605f5be87',
						'label' => 'Color Classes',
						'name' => 'color_classes',
						'type' => 'textarea',
						'instructions' => '<em class="dev-only">Field Name: color_classes<br />Field Key: field_6213605f5be87</em>',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33',
							'class' => 'dev-only',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => 3,
						'new_lines' => '',
						'readonly' => 1,
					),
				),
			),
			array(
				'key' => 'field_6216604e5be82',
				'label' => 'Company Information',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_6216605f5be87',
				'label' => 'Company Name',
				'name' => 'company_name',
				'type' => 'text',
				'instructions' => '<em class="dev-only">Field Name: company_name<br />Field Key: field_6216605f5be87</em>',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_6216607a5be84',
				'label' => 'Email',
				'name' => 'email',
				'type' => 'email',
				'instructions' => '<em class="dev-only">Field Name: email<br />Field Key: field_6216607a5be84</em><p>shortcode: [email text="<em>link text</em>"]</p>',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '49',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_6216609c5be82',
				'label' => 'Phone Number',
				'name' => 'phone_number',
				'type' => 'text',
				'instructions' => '<em class="dev-only">Field Name: phone_number<br />Field Key: field_6216609c5be82</em><p>shortcode: [phone-number text="<em>link text"</em>]</p>',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '49',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_62744bc94a6b1',
				'label' => 'Physical Address',
				'name' => '',
				'type' => 'accordion',
				'instructions' => '<em class="dev-only">Field Name: physical_address<br />Field Key: field_62744bc94a6b1</em>',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'open' => 0,
				'multi_expand' => 0,
				'endpoint' => 0,
			),
			array(
				'key' => 'field_62744c394a6b5',
				'label' => 'Street',
				'name' => 'physical_street',
				'type' => 'textarea',
				'instructions' => '<em class="dev-only">Field Name: physical_street<br />Field Key: field_62744c394a6b5</em>',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 2,
				'new_lines' => 'br',
			),
			array(
				'key' => 'field_62744c5f4a6b7',
				'label' => 'City',
				'name' => 'physical_city',
				'type' => 'text',
				'instructions' => '<em class="dev-only">Field Name: physical_city<br />Field Key: field_62744c5f4a6b7</em>',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_62744c6a4a6b8',
				'label' => 'State',
				'name' => 'physical_state',
				'type' => 'text',
				'instructions' => '<em class="dev-only">Field Name: physical_state<br />Field Key: field_62744c6a4a6b8</em>',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_62744c984a6b9',
				'label' => 'Zip',
				'name' => 'physical_zip',
				'type' => 'text',
				'instructions' => '<em class="dev-only">Field Name: physical_zip<br />Field Key: field_62744c984a6b9</em>',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_62744be04a6b2',
				'label' => 'Physical Address Endpoint',
				'name' => '',
				'type' => 'accordion',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'open' => 0,
				'multi_expand' => 0,
				'endpoint' => 1,
			),
			array(
				'key' => 'field_62744c0b4a6b3',
				'label' => 'Mailing Address',
				'name' => '',
				'type' => 'accordion',
				'instructions' => '<em class="dev-only">Field Name: mailing_address<br />Field Key: field_62744c0b4a6b3</em>',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'open' => 0,
				'multi_expand' => 0,
				'endpoint' => 0,
			),
			array(
				'key' => 'field_62744d434a6bb',
				'label' => 'Street',
				'name' => 'mailing_street',
				'type' => 'textarea',
				'instructions' => '<em class="dev-only">Field Name: mailing_street<br />Field Key: field_62744d434a6bb</em>',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 2,
				'new_lines' => 'br',
			),
			array(
				'key' => 'field_62744d554a6bc',
				'label' => 'City',
				'name' => 'mailing_city',
				'type' => 'text',
				'instructions' => '<em class="dev-only">Field Name: mailing_city<br />Field Key: field_62744d554a6bc</em>',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_62744d874a6bd',
				'label' => 'State',
				'name' => 'mailing_state',
				'type' => 'text',
				'instructions' => '<em class="dev-only">Field Name: mailing_state<br />Field Key: field_62744d874a6bd</em>',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_62744d944a6be',
				'label' => 'Zip',
				'name' => 'mailing_zip',
				'type' => 'text',
				'instructions' => '<em class="dev-only">Field Name: mailing_zip<br />Field Key: field_62744d944a6be</em>',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_62744c204a6b4',
				'label' => 'Mailing Address Endpoint',
				'name' => '',
				'type' => 'accordion',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'open' => 0,
				'multi_expand' => 0,
				'endpoint' => 1,
			),
			array(
				'key' => 'field_61e08723b7bbd',
				'label' => '',
				'name' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => 'logo-message',
				),
				'message' => '<h3>Logo</h3><br /><p><em>Please add an image <strong>OR</strong> an image url</em></p>',
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
			array(
				'key' => 'field_61a633b815540',
				'label' => '',
				'name' => 'logo',
				'type' => 'image',
				'instructions' => '<em class="dev-only">Field Name: logo<br />Field Key: field_61a633b815540</em>',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '49',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_61e091c091bc2',
				'label' => '',
				'name' => 'image_url',
				'type' => 'url',
				'instructions' => '<em class="dev-only">Field Name: image_url<br />Field Key: field_61e091c091bc2</em>',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '49',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key' => 'field_627bd8be73608',
				'label' => 'Banner',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_61a332bd1d944',
				'label' => 'Activate?',
				'name' => 'banner_active',
				'type' => 'true_false',
				'instructions' => '<em class="dev-only">Field Name: banner_active<br />Field Key: field_61a332bd1d944</em>',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '20',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_628b9f6bae548',
				'label' => 'Background Color',
				'name' => 'background_color',
				'type' => 'color_picker',
				'instructions' => '<em class="dev-only">Field Name: background_color<br />Field Key: field_628b9f6bae548</em>',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '20',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'enable_opacity' => 0,
				'return_format' => 'string',
			),
			array(
				'key' => 'field_628b9f81d21c9',
				'label' => 'Text',
				'name' => 'text',
				'type' => 'wysiwyg',
				'instructions' => '<em class="dev-only">Field Name: text<br />Field Key: field_628b9f81d21c9</em>',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '58',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 0,
				'delay' => 0,
			),
			array(
				'key' => 'field_61a632871d943',
				'label' => 'Maintenance/Debugging',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_633085e86f965',
				'label' => 'IP Address',
				'name' => 'ip_address',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_6354c7651000d',
							'operator' => '==',
							'value' => '1',
						),
					),
					array(
						array(
							'field' => 'field_63f8e9047d7c6',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_61a632bd1d944',
				'label' => 'Enable Maintenance Mode?',
				'name' => 'enable_maintenance_mode',
				'type' => 'true_false',
				'instructions' => '<em class="dev-only">Field Name: enable_maintenance_mode<br />Field Key: field_61a632bd1d944</em>',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_6354c7651000d',
				'label' => 'Enable Debugging?',
				'name' => 'enable_debug',
				'type' => 'true_false',
				'instructions' => '<em class="dev-only">Field Name: enable_debug<br />Field Key: field_6354c7651000d</em>',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => 'dev-only',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_63f8e9047d7c6',
				'label' => 'Suspend Site?',
				'name' => 'suspend_site',
				'type' => 'true_false',
				'instructions' => '<em class="dev-only">Field Name: suspend_site<br />Field Key: field_63f8e9047d7c6</em>',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => 'dev-only',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_63f8e9547d7c6',
				'label' => 'Enable Coming Soon?',
				'name' => 'enable_coming_soon',
				'type' => 'true_false',
				'instructions' => '<em class="dev-only">Field Name: enable_coming_soon<br />Field Key: field_63f8e9547d7c6</em>',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => 'dev-only',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_668c176190a05',
				'label' => 'Tutorials',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
				'selected' => 0,
			),
			array(
				'key' => 'field_668c177490a06',
				'label' => '<h1>Tutorials</h1>',
				'name' => '',
				'aria-label' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'new_lines' => '',
				'esc_html' => 0,
			),
			array(
				'key' => 'field_62dff6febee11',
				'label' => 'AIC Options',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_62dff88dbee13',
				'label' => 'Disable Editor',
				'name' => 'disable_editor_list',
				'type' => 'relationship',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => 'dev-only',
					'id' => '',
				),
				'post_type' => '',
				'taxonomy' => '',
				'filters' => array(
					0 => 'post_type',
					1 => 'taxonomy',
				),
				'elements' => '',
				'min' => '',
				'max' => '',
				'return_format' => 'id',
			),
			array(
				'key' => 'field_668c1d54c2543',
				'label' => '<h1>Tutorials</h1>',
				'name' => 'tutorial_section',
				'aria-label' => '',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_668c1cb24733a',
						'label' => 'Tutorial Column Break',
						'name' => 'column_break',
						'aria-label' => '',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'min' => '',
						'max' => '',
						'placeholder' => '',
						'step' => '',
						'prepend' => '',
						'append' => '',
					),
					array(
						'key' => 'field_67212796bace5',
						'label' => 'Border Color',
						'name' => 'border_color',
						'aria-label' => '',
						'type' => 'color_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'enable_opacity' => 0,
						'return_format' => 'string',
						'allow_in_bindings' => 0,
					),
					array(
						'key' => 'field_668c1d78c2544',
						'label' => 'Tutorial Videos',
						'name' => 'tutorial_videos',
						'aria-label' => '',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'block',
						'pagination' => 0,
						'min' => 0,
						'max' => 0,
						'collapsed' => 'field_668c1d97c2545',
						'button_label' => 'Add Tutorial',
						'rows_per_page' => 20,
						'sub_fields' => array(
							array(
								'key' => 'field_668c1d97c2545',
								'label' => 'Title',
								'name' => 'title',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '33',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'maxlength' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'parent_repeater' => 'field_668c1d78c2544',
							),
							array(
								'key' => 'field_668c1da5c2546',
								'label' => 'Video File',
								'name' => 'video_file',
								'aria-label' => '',
								'type' => 'file',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '33',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'url',
								'library' => 'all',
								'min_size' => '',
								'max_size' => '',
								'mime_types' => '',
								'parent_repeater' => 'field_668c1d78c2544',
							),
							array(
								'key' => 'field_672122d04a977',
								'label' => 'Thumbnail',
								'name' => 'thumbnail',
								'aria-label' => '',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '33',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'url',
								'library' => 'all',
								'min_size' => '',
								'max_size' => '',
								'mime_types' => '',
								'parent_repeater' => 'field_668c1d78c2544',
							),
						),
					),
				),
			),
			array(
				'key' => 'field_66be11970d6e1',
				'label' => '<h1 style="text-align: center;">Visibility</h1>',
				'name' => '',
				'aria-label' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
			array(
				'key' => 'field_62dff92f6323f',
				'label' => 'Tabs Visibility',
				'name' => 'tabs_visibility',
				'type' => 'checkbox',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => 'dev-only',
					'id' => '',
				),
				'choices' => array(
					'field_61a631c11d93f' => 'Theme Colors',
					'field_6216604e5be82' => 'Company Information',
					'field_627bd8be73608' => 'Banner',
					'field_61a632871d943' => 'Maintence/Debugging',
					'field_61a635871d943' => 'Support Ticket',
					'field_668c176190a05' => 'Tutorials'
				),
				'allow_custom' => 0,
				'default_value' => array(
				),
				'layout' => 'vertical',
				'toggle' => 0,
				'return_format' => 'value',
				'save_custom' => 0,
			),
			array(
				'key' => 'field_62e04c22c74e3',
				'label' => 'Other Options Visibility',
				'name' => 'other_options_visibility',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'collapsed' => 'field_62e04c41c74e8',
				'min' => 0,
				'max' => 0,
				'layout' => 'block',
				'button_label' => 'Add Field',
				'sub_fields' => array(
					array(
						'key' => 'field_62e04c41c74e8',
						'label' => 'Field Name',
						'name' => 'field_name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '49',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_62e04c57c74e0',
						'label' => 'Field Key',
						'name' => 'field_key',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '49',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
				),
			),
			array(
				'key' => 'field_66be1272e2c47',
				'label' => 'Developer Access IDs',
				'name' => 'developer_access_ids',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'pagination' => 0,
				'min' => 0,
				'max' => 0,
				'collapsed' => 'field_66be128c2e8f7',
				'button_label' => 'Add ID',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_66be128c2e8f7',
						'label' => '',
						'name' => 'dev_access_id',
						'aria-label' => '',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'min' => '',
						'max' => '',
						'placeholder' => '',
						'step' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_66be1272e2c47',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'aic-theme-options'
				)
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'field',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));
}

?>
